### PR TITLE
Remove GTE conditional from check routine to support rollback scenarios

### PR DESCRIPTION
**Pull request by jlsalmon**
Revival of #113 with comments addressed and build fixed.

Looking forward to having this feature! :)

### CODE REVIEW

**Review by taylorsilva — APPROVED** [review]
Thanks for adding in all the suggested changes!

**Comment by jlsalmon** [comment]
Thanks for taking a look at this so quickly @taylorsilva, much appreciated. When do you think you will be making the next release?

**Comment by taylorsilva** [comment]
Next release should be soon. Probably next week or two!

**Comment by glompix** [comment]
Thank you!

**Pull request merged**
