### PR TITLE
git-tag with prefix of the tag

### PR DESCRIPTION
**Pull request by ggeorgiev**
This is based on the @holstvoogd work for preparing git-tag.

This version eliminates the branch which does not seem to make a lot of sense for a git repo tagging.

Also, supports for tag prefix - where tags instead '1.2.3' will look as 'v1.2.3'. This also allows for versioning of more than one component in the same repo.

---
This change is [Reviewable](https://reviewable.io/reviews/concourse/semver-resource/29)

### CODE REVIEW

**Comment by vise890** [comment]
are there any plans for this getting merged? I'm setting up the infra for a new team and i'd love to use this

**Comment by gabro** [comment]
same here! Is this still unscheduled?

**Comment by analytically** [comment]
Same here!

**Comment by analytically** [comment]
Very handy in combination with https://github.com/dwijnand/sbt-dynver

**Comment by harnash** [comment]
Hi.
 Any chance for a review? I would really like this being implemented.

**Comment by ggeorgiev** [comment]
I just discover a severe logical issue with the current implementation (even I successfully used it for few months). It, by the way, exists with git driver as well.

The problem is that when the version is updated - there is no assurance that the version that is tagged is the one that was validated from the pipeline. In case a new commit is added meanwhile, you might finish tagging a change that even does not build.

I withdrawing this pr until I fix that.

**Comment by ggeorgiev** [comment]
Actually, the file one has no way to be fixed. Maybe the team should commit to this one and make it right - assuming they can dedicate more time than me.

**Comment by harnash** [comment]
@ggeorgiev could you file an issue with more detailed explanation? I can guess the problem lies in the way bumping version mechanisms is implements (fetches brand new code from a given branch when setting new version). It would be helpful.

**Comment by ggeorgiev** [comment]
@harnash. sure, please check: #34

**Pull request closed without merging**
