### PR TITLE
Git Tag backend

### PR DESCRIPTION
**Pull request by holstvoogd**
use annotated tags in git to store version

### CODE REVIEW

**Comment by vito** [comment]
Awesome! 🎊

One thing that would make it better though: I think it should be told which SHA to tag via a param to `put`. This is because in most cases the repository being versioned will be what triggered the version bump, and so the exact commit should be passed along and tagged. For example, our pipeline at https://ci.concourse.ci would do this in the `rc` `major`, `minor`, `patch`, and `shipit` jobs (and we'd update them to take in the `concourse` resource accordingly if they're not already).

So, today's `rc` job, which looks like this:

```yaml
jobs:
  - get: concourse
    trigger: true
    passed: [atc, fly, go-concourse, blackbox, tsa, baggageclaim]
  - get: garden-runc
  - get: version
    params: {pre: rc}
  - put: version
    params: {file: version/version}
```

...would become...

```yaml
jobs:
  - get: concourse
    trigger: true
    passed: [atc, fly, go-concourse, blackbox, tsa, baggageclaim]
  - get: garden-runc
  - get: version
    params: {pre: rc}
  - put: version
    params: {repository: concourse, file: version/version}
```

(Only difference is the last line.)

The `repository` param would point to the repository whose current `HEAD` should be the commit to tag.

At that point I'm not sure if it'd even need this resource to be configured with a `branch` - it may make more sense to just have it base everything on an already-fetched repository. It'd still need the rest though (`private_key`, etc.) to know where to push.

**Comment by holstvoogd** [comment]
👍 that sound like a good idea. I'll see what I can do!

But I'm not quite sure if we can drop the branch, I think we will at least need it for Check. It can't access other resources during a Check, right?
Actually I would like to keep supporting the current mechanism too for Get so it can be used to monitor a branch for new version tags and have that trigger a Job.

I'm going to churn on this a bit and see I anything else floats up ;)

**Comment by holstvoogd** [comment]
hmm, I'm starting to think my idea about having a new semver version trigger a build is not really a sensible approach with tags, since you will probably then need to go ahead and checkout that version to build. Not really compatible with how Get works.

**Comment by vito** [comment]
implementing 'check' and 'get' makes sense. wonder if they could just use
ls-remote though so you don't even need to clone?

'get' should just create the version files

**Comment by holstvoogd** [comment]
I've added support for the aforementioned, but I'm not quite happy with it yet. 

I think it needs some refactoring and it still needs to clone the repo for check (& put if you don't have a repo to go with it, but that is inevitable afaik). Still want to clean that up with ls-remote etc.

**Comment by holstvoogd** [comment]
Sorry for the delay, I've been working on getting it working without a clone etc. Unfortunately using ls-remote to find the latest tag is not safe, it cannot be scoped per branch so that last tag might just be from another branch.

The best I can do is fetch everything only when reading a version and then using ls-remote to get the reference for the branch head to tag on write. I'll push an update for review as soon as I have it tested

**Comment by holstvoogd** [comment]
updated. It is a bit more efficient, but unfortunately I can't work around having to fetch everything.

**Comment by vito** [comment]
Sorry for the delay.

Aren't tags global anyway? It shouldn't matter which branch its originating commit lives on.

**Comment by pivotal-issuemaster** [comment]
@holstvoogd Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/semver-resource&pullRequestId=22) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by vito** [comment]
@holstvoogd Any update on this? Would be great to have - I figure given that tags are global it should be possible to not clone. But you've looked into it more than me so maybe I'm missing something.

**Comment by willejs** [comment]
@holstvoogd did you ever manage to finish this?

**Comment by holstvoogd** [comment]
I'm not quite sure where I've left this tbh. I was working on it with regards to a work project, but it was no longer needed so I couldn't complete it there. And since I left that company I also lost any non-committed code.
I'm pretty sure it was all working, but we never really figured out how to handle branches with regards to tags. Or even if they should be relevant. I'll see if I can review my work and update the PR tonight

**Comment by willejs** [comment]
@holstvoogd ahh cheers for replying. Branches shouldent be an issue, as a tag is against the sha1 hash, and independent of a branch. :) so it may all work!

**Comment by pivotal-issuemaster** [comment]
@holstvoogd Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/semver-resource&pullRequestId=22)!

**Comment by willejs** [comment]
@holstvoogd This looks good, Im going to try it today. The branch name isnt required when tagging, it basically just means tag HEAD on that branch. So actually if youve checked out a branch and you tag against another branch youve specified, you could create a tag for a different commit to the one you are currently on. [This explains it better](http://stackoverflow.com/a/27154277)
I think if you remove the branch bit from the tagging, it looks good! 👍

**Comment by holstvoogd** [comment]
@willejs You're right, currently it will screw up you tags if you don't set the branch to the same as on the checked out repo you are working with. Infact, if you don't set a branch it will just tag the remote HEAD >_< I'll fix that :)
The branch was there primarily for scoping, but that isn't needed when working with an existing repo resource. You'd always want to read from (or tag) whatever is checked out at that time.

However, when you are using a remote repo, being able to scope by branch does seem to make sense. i.e tag the HEAD of the 'staging' branch with the new version. Although I can't really imagine why you would not have the same commit checked out during the build...

**Comment by holstvoogd** [comment]
Hmm. This won't work the way I've set it up. It kinda breaks the concourse resource model by accepting a repo path as source config since the check won't work. I have to change it so that the whole 'you can use an existing repo' works through params.

So what I'll do:
- You MUST configure a repo uri on the resource, it pulls all tags globally. No branch scoping allowed at for now.
- You MAY pass a repo path to get to get the latest tag describing the checked out commit.
- You MAY pass a repo path (or a ref, or a path to a file with a ref?) to set what commit to tag.

**Comment by vito** [comment]
@holstvoogd Yeah; I don't think branches factor into this at all. Tags are across *all* branches and apply to commits, which can live on any or multiple branches at a given time. There's no scoping that you can really do, aside from having different tag prefixes or something.

It makes sense to me for `source` to be configured with the URI, so that it can check for tags against the repo (across all branches, i.e. `git ls-remote`). It also makes sense to me for `put` to be given a path to a repository, whose `HEAD` points to the commit to tag. IMO that should be the only way to tag; it doesn't make sense to me to just tag a remote branch in whatever state it's in, as commits may have snuck in between the job triggering and wanting to tag what it triggered with. Alternative ways of supplying the commit could also make sense, the point being that it should be given a ref in some way - a checked-out repo seems like the most natural thing given how git resources are already used today.

Also I'm not sure what your second bullet point means.

**Comment by willejs** [comment]
@holstvoogd I know you arnt working with concourse anymore so not sure if your going to finish this? I say this because im tempted to have a go...

**Comment by holstvoogd** [comment]
@willejs yeah, please feel free to pick this up, I don't have the time or the resources to actually test anything I do with this

**Comment by jtarchie** [comment]
@holstvoogd, what would it take to bring this back to life? Want to pair?

**Comment by willejs** [comment]
@jtarchie It would be amazing if you could pick it up!

**Pull request closed without merging**
