### PR TITLE
adding support to skip ssl validation

### PR DESCRIPTION
**Pull request by calebwashburn**
Addresses issue https://github.com/concourse/semver-resource/issues/49

### CODE REVIEW

**Comment by jtarchie** [comment]
@calebwashburn, thanks for the PR!

1. Are you able to provide tests for this feature?
2. Can you confirm that the HttpClient used with AWS (before this PR) was `DefaultClient`? The `DefaultClient` has really bad timeout default, I want to believe that AWS didn't go with those defaults.

Cheers!

**Comment by calebwashburn** [comment]
@jtarchie I'll add some tests and run down the 2nd question as well.

**Comment by calebwashburn** [comment]
@jtarchie added some tests and validated that AWS sdk just uses DefaultClient.  This is also the same code used in s3-resource https://github.com/concourse/s3-resource/blob/master/s3client.go#L101-L108

**Comment by jtarchie** [comment]
Thanks. We'll take a look at this.

**Comment by vito** [comment]
thanks!

**Pull request merged**
